server:
  port: 10000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: user-service
        uri: http://localhost:9000
        predicates:
          - Path=/user/**
  main:
    web-application-type: reactive